version: "3.9"

services:
  forward-proxy-server:
    build:
      context: ./http-forward-proxy
      dockerfile: Dockerfile
    container_name: forward-proxy-server
    depends_on:
      - reverse-proxy-server
    networks:
      - public-net
      - internal-net
    ports:
      - "6443:6443"
    environment:
      - TLS_SERVER_CERT=/etc/ssl/certs/server.crt
      - TLS_SERVER_KEY=/etc/ssl/keys/server.key
    volumes:
      - ./tls-configs/forward-proxy/certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./tls-configs/forward-proxy/keys/server.key:/etc/ssl/keys/server.key:ro
    command: ["./proxy-server", "-host", "0.0.0.0", "-port", "6443"]

  reverse-proxy-server:
    build:
      context: ./http-reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy-server
    depends_on:
      - http-server-1
      - http-server-2
      - redis-server
    networks:
      - internal-net
    ports:
      - "7443:7443"
    environment:
      - TLS_CLIENT_CERT=/etc/ssl/certs/web-server-client.crt
      - TLS_CLIENT_KEY=/etc/ssl/keys/web-server-client.key
      - TLS_CA=/etc/ssl/certs/web-server-ca.crt
      - TLS_SERVER_CERT=/etc/ssl/certs/reverse-proxy-server.crt
      - TLS_SERVER_KEY=/etc/ssl/keys/reverse-proxy-server.key
    volumes:
      - ./tls-configs/web-server/certs/client.crt:/etc/ssl/certs/web-server-client.crt:ro
      - ./tls-configs/web-server/certs/ca.crt:/etc/ssl/certs/web-server-ca.crt:ro
      - ./tls-configs/web-server/keys/client.key:/etc/ssl/keys/web-server-client.key:ro
      - ./tls-configs/reverse-proxy/certs/server.crt:/etc/ssl/certs/reverse-proxy-server.crt:ro
      - ./tls-configs/reverse-proxy/keys/server.key:/etc/ssl/keys/reverse-proxy-server.key:ro
    command: ["./reverse-proxy-server", "-host", "0.0.0.0", "-port", "7443", "-map", "/server1=http-server-1:8443,/server2=http-server-2:9443"]

  http-server-1:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-server-1
    # ports:
    #   - "8081:8081"
    command: ["./server", "-host", "0.0.0.0", "-port", "8443"]
    restart: unless-stopped
    networks:
      - internal-net
    environment:
      - TLS_SERVER_CERT=/etc/ssl/certs/server.crt
      - TLS_SERVER_KEY=/etc/ssl/keys/server.key
      - TLS_CA=/etc/ssl/certs/ca.crt
    volumes:
      - ./http-server/index_server_1.html:/root/index.html:ro
      - ./tls-configs/web-server/certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./tls-configs/web-server/certs/ca.crt:/etc/ssl/certs/ca.crt:ro
      - ./tls-configs/web-server/keys/server.key:/etc/ssl/keys/server.key:ro

  http-server-2:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-server-2
    # ports:
    #   - "8081:8081"
    command: ["./server", "-host", "0.0.0.0", "-port", "9443"]
    restart: unless-stopped
    networks:
      - internal-net
    environment:
      - TLS_SERVER_CERT=/etc/ssl/certs/server.crt
      - TLS_SERVER_KEY=/etc/ssl/keys/server.key
      - TLS_CA=/etc/ssl/certs/ca.crt
    volumes:
      - ./http-server/index_server_2.html:/root/index.html:ro
      - ./tls-configs/web-server/certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./tls-configs/web-server/certs/ca.crt:/etc/ssl/certs/ca.crt:ro
      - ./tls-configs/web-server/keys/server.key:/etc/ssl/keys/server.key:ro

  redis-server:
    image: "redis:alpine"
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal-net
    
networks:
  internal-net:
    driver: bridge
  public-net:
    driver: bridge